# FROM node:20-alpine (last push 1 week ago)  //Node or operating system image

# COPY ./package.json .
# COPY ./package-lock.json .

# RUN npm install

# COPY ./server.js .  


FROM node:20-alpine

WORKDIR /app

COPY package.json /app
COPY package-lock.json /app

RUN npm install

COPY . /app

CMD ["node", "server.js"]